version: "2.1"
services:
  database:
    container_name: database
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: thermostat
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 2
    networks:
      - backend
  thermostat:
    build:
      context: ./ThermostatManagementSystem
      dockerfile: ./Dockerfile
    image: thermostat-management-system
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:
    driver: bridge